### ISSUE TITLE
autotile info couldn't find.

### ISSUE THREAD

**Issue by arturertel** [XLIVE99/Gridmap_Autotile#2]
.agrid can be saved in any folder, but for the gridmap it can only be loaded from the root directory.

https://youtu.be/1oPwsmXG320

**Comment by XLIVE99** [comment]
You can see the AutoGrid logs "File couldn't find at res://agrid/bitmask.agrid" in console at 2:04. Because of the limitations if Meshlibrary didn't assign while you selecting a GridMap node, AutoGrid will not detect it as usable GridMap. So if you assign a new MeshLibrary you need to re-select that GridMap in order to load .agrid file.
I will change AutoGrid logs to appear more. And I will show "Create Autotile Info" and "Reload Autotile Info" buttons if "Edit mode" selected because these buttons have nothing to do with a GridMap node.
Edit: I updated the AutoGrid, you will see "AutoGrid is ready to use" printed on console if everything is right (and autotile is enabled).

**Comment by XLIVE99** [comment]
It seems there is no problem here anymore.
