### ISSUE TITLE
Autotile not placing right tiles

### ISSUE THREAD

**Issue by stesproject** [XLIVE99/Gridmap_Autotile#5]
I'm trying to paint some tiles but it looks like only "closed" tiles autotiles correctly, if I open some angles I get the wrong tiles as shown in the image:
![Screenshot 2024-06-21 192852](https://github.com/XLIVE99/AutoGrid/assets/32966173/1c12474d-8db9-46ce-9da0-15070297ae0f)

I read the documentation and tried to toggle Performance mode, but it does not make any difference.
I'm using version 1.2 on Godot 4.2.2 with the demo project.

PS: Sorry I didn't mean to post in [that](https://github.com/godotengine/godot-proposals/issues/114#issuecomment-2183172924) discussion, I got your reply notification via email and it misleaded me (I replied directly to the email).

**Comment by XLIVE99** [comment]
I couldn't get the same result as yours. But it seems like you are trying to place a different tile than the autogrid recognizes. While autotile can still work with this, in some cases, it can place wrong tiles. Please select the tile ends with "_agrid".
![image_2024-06-21_223908010](https://github.com/XLIVE99/AutoGrid/assets/30470295/0f666c2a-700c-435c-b468-91b551791190)

And can you make sure you are painting with these settings:
![image_2024-06-21_224234555](https://github.com/XLIVE99/AutoGrid/assets/30470295/8a8dfeae-b293-49db-8e15-ffc5fdae7a3b)

If this doesn't solve the problem can you share more details?

**Comment by stesproject** [comment]
Thank you very much, the autotile mode wasn't set to "Minimal 3x3". Now it works :)
Is it possible to draw autotiles also on the X axes? If yes, how should I set up the tiles?
![image](https://github.com/XLIVE99/AutoGrid/assets/32966173/7725370f-7831-432d-b74b-50b532181162)

**Comment by XLIVE99** [comment]
Yes, you can draw autotile in all three axises. Demo project only uses X & Z axis because it has only ground tiles. You have to create your bitmasks to use it in Y & Z axis. Please read the "Creating Bitmasks" section of the "HELP.pdf" file inside "addon" folder. After you have created the bitmasks, you have to set "Tile Normal Axis" to "X Axis"

**Comment by stesproject** [comment]
> Yes, you can draw autotile in all three axises. Demo project only uses X & Z axis because it has only ground tiles. You have to create your bitmasks to use it in Y & Z axis. Please read the "Creating Bitmasks" section of the "HELP.pdf" file inside "addon" folder. After you have created the bitmasks, you have to set "Tile Normal Axis" to "X Axis"

Hi, I read the documentation but there's many things not explained.
1. Where do I set the tile texture?
2. How do I set up the bit mask?
3. Shouldn't be enough to set "Tile Normal Axis" to "X Axis" to paint the demo tiles on the X axis with autotile working?

**Comment by XLIVE99** [comment]
1. It depends on your tiles, you should check the [Godot 3D material documentation](https://docs.godotengine.org/en/stable/tutorials/3d/standard_material_3d.html) for it. I upgraded from Godot 3 to Godot 4. The tiles scene (DEMO/res_2D/Ground_MeshLibrary.tscn) is all white right now because of the upgrade. But built meshlibrary from Godot 3 is still impact, that's (I think) why tiles have a texture on it while we can't see it in the scene.
2. You will have to create a scene for [MeshLibrary](https://docs.godotengine.org/en/stable/tutorials/3d/using_gridmaps.html). After creating MeshInstance for each tile, you can enable "Edit Mode" and then there will be a "AutoGrid" button as shown in the documentation. You might need to re-select (Selecting another node then selectin MeshInstance again) the MeshInstance after enabling the "Edit Mode" if "AutoGrid" button doesn't show up. Then you can create bitmasks from the "AutoGrid" button for the selected tile (MeshInstance).
3. AutoGrid works same as [TileMap's autotile](https://docs.godotengine.org/en/3.4/tutorials/2d/using_tilemaps.html#autotiles) but just 3D version of it. In 2D there is only 2 axises to worry about but in 3D you have to specify the normal axis of the tiles to correctly calculate bit values, AutoGrid was only calculating as every tile's normal axis is Y in version 1.0, but it led to a problem as you can see [here](https://github.com/XLIVE99/AutoGrid/issues/3). Tile Normal Axis only changes the check order of the tiles to correctly place tiles, that option doesn't rotate the bitmasks. Therefore that's why you have to create correct bitmasks for that axis.

I will record a video both in Godot 3 and Godot 4 to show how to use the plugin but I don't have enough time to record it as of now. And unfortunately I won't have time for like a month but I can try to squeeze it in my schedule. There is also [another closed issue](https://github.com/XLIVE99/AutoGrid/issues/4) with detailed steps which might help you.
